In [1]:
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')

In [12]:
year = np.array(['Second']*60 + ['Third']*40)
major = np.array(['Undeclared']*30 + ['Declared']*30 + ['Undeclared']*8 + ['Declared']*32)
students = Table().with_columns(
    'Year', year,
    'Major', major
)
students.show()

In [14]:
students.sample(10)

Year   | Major
Second | Declared
Second | Undeclared
Second | Declared
Second | Undeclared
Third  | Declared
Second | Undeclared
Third  | Declared
Second | Declared
Second | Declared
Third  | Declared

In [15]:
students.pivot('Major', 'Year')

Year   | Declared | Undeclared
Second | 30       | 30
Third  | 32       | 8

In [16]:
30 / (30 + 32)

0.4838709677419355

In [17]:
0.004 * 0.99

0.00396

In [18]:
0.996 * 0.005

0.00498

In [20]:
(0.00396) / (0.00396 + 0.00498)

0.44295302013422816

In [37]:
prior_probability_disease = 0.004
n_d = int(prior_probability_disease * 100000)
n_nd = 100000 - n_d
n_pos_d = int(0.99 * n_d)
n_neg_d = n_d - n_pos_d
n_pos_nd = int(0.005 * n_nd)
n_neg_nd = n_nd - n_pos_nd
condition = np.array(['Disease']*n_d + ['No Disease']*n_nd)
test_results_d = np.array(['Positive']*n_pos_d + ['Negative']*n_neg_d)
test_results_nd = np.array(['Positive']*n_pos_nd + ['Negative']*n_neg_nd)
test = np.append(test_results_d, test_results_nd)
t = Table().with_columns(
    'True Condition', condition,
    'Test Result', test
)
t

True Condition | Test Result
Disease        | Positive
Disease        | Positive
Disease        | Positive
Disease        | Positive
Disease        | Positive
Disease        | Positive
Disease        | Positive
Disease        | Positive
Disease        | Positive
Disease        | Positive
... (99990 rows omitted)

In [38]:
t.pivot('Test Result', 'True Condition')

True Condition | Negative | Positive
Disease        | 4        | 396
No Disease     | 99102    | 498

In [39]:
prior_probability_disease = 0.05
n_d = int(prior_probability_disease * 100000)
n_nd = 100000 - n_d
n_pos_d = int(0.99 * n_d)
n_neg_d = n_d - n_pos_d
n_pos_nd = int(0.005 * n_nd)
n_neg_nd = n_nd - n_pos_nd
condition = np.array(['Disease']*n_d + ['No Disease']*n_nd)
test_results_d = np.array(['Positive']*n_pos_d + ['Negative']*n_neg_d)
test_results_nd = np.array(['Positive']*n_pos_nd + ['Negative']*n_neg_nd)
test = np.append(test_results_d, test_results_nd)
t = Table().with_columns(
    'True Condition', condition,
    'Test Result', test
)
t.pivot('Test Result', 'True Condition')

True Condition | Negative | Positive
Disease        | 50       | 4950
No Disease     | 94525    | 475